### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by yuanf225** [lineagedr/mod-bountyhunter#1]
[ 83%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-bountyhunter/src/BountyHunter.cpp.o
In file included from /home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.cpp:1:
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.h:69:5: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
    const uint32 GetTokenId() const;
    ^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.h:70:5: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
    const uint32 GetTokenMaxAmount() const;
    ^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.h:71:5: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
    const uint32 GetGoldMaxAmount() const;
    ^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.h:72:5: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
    const uint32 GetHonorMaxAmount() const;
    ^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.h:91:5: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
    const uint32 GetBountyPriceAmount(ObjectGuid playerGuid);
    ^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.cpp:23:1: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
const uint32 BountyHunter::GetTokenId() const
^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.cpp:28:1: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
const uint32 BountyHunter::GetTokenMaxAmount() const
^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.cpp:33:1: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
const uint32 BountyHunter::GetGoldMaxAmount() const
^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.cpp:38:1: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
const uint32 BountyHunter::GetHonorMaxAmount() const
^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.cpp:121:1: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
const uint32 BountyHunter::GetBountyPriceAmount(ObjectGuid playerGuid)
^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.cpp:149:17: warning: enumeration value 'NONE' not handled in switch [-Wswitch]
        switch (m_BountyContainer[bounty->GetGUID()].type)
                ^
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.cpp:283:21: warning: enumeration value 'NONE' not handled in switch [-Wswitch]
            switch (bountyInfo.type)
                    ^
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.cpp:309:13: warning: enumeration value 'NONE' not handled in switch [-Wswitch]
    switch (m_BountyGossipContainer[player->GetGUID()].priceType)
            ^
[ 84%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-bountyhunter/src/BountyHunter_Loader.cpp.o
[ 84%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-bountyhunter/src/BountyHunter_SC.cpp.o
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter_SC.cpp:7:1: warning: '/*' within block comment [-Wcomment]
/*******************************/
^
In file included from /home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter_SC.cpp:9:
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.h:69:5: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
    const uint32 GetTokenId() const;
    ^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.h:70:5: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
    const uint32 GetTokenMaxAmount() const;
    ^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.h:71:5: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
    const uint32 GetGoldMaxAmount() const;
    ^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.h:72:5: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
    const uint32 GetHonorMaxAmount() const;
    ^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.h:91:5: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
    const uint32 GetBountyPriceAmount(ObjectGuid playerGuid);
    ^~~~~~
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter_SC.cpp:24:35: warning: enumeration value 'NONE' not handled in switch [-Wswitch]
            switch(sBountyHunter->GetBountyPriceType(bounty->GetGUID()))
                                  ^
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter_SC.cpp:120:68: warning: unused parameter 'sender' [-Wunused-parameter]
    bool OnGossipSelect(Player* player, Creature* creature, uint32 sender, uint32 action) override
                                                                   ^
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter_SC.cpp:181:17: warning: enumeration value 'NONE' not handled in switch [-Wswitch]
        switch (action)
                ^

**Comment by yuanf225** [comment]
Hey buddy, maybe it needs to be updated

**Comment by lineagedr** [comment]
Fixed in: https://github.com/lineagedr/mod-bountyhunter/commit/c17d3f7430fd817ec411e6db3e53bd2092b5ba75
