### ISSUE TITLE
linux compile error

### ISSUE THREAD

**Issue by yuanf225** [lineagedr/mod-bountyhunter#2]
AC：[3daa8e2](https://github.com/azerothcore/azerothcore-wotlk/commit/3daa8e2146b97346c61b08f5d23751e27f8692f2)
[ 22%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_cast.cpp.o
/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter.cpp:145:42: fatal error: member access into incomplete type 'const Player'
    const std::string bountyName = bounty->GetName();
                                         ^
/home/azerothcore-wotlk/src/server/game/Achievements/AchievementMgr.h:81:7: note: forward declaration of 'Player'
class Player;
      ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:258: modules/CMakeFiles/modules.dir/mod-bountyhunter/src/BountyHunter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 23%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/CoreAI/ReactorAI.cpp.o
make[1]: *** [CMakeFiles/Makefile2:1362: modules/CMakeFiles/modules.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 23%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_character.cpp.o

**Comment by lineagedr** [comment]
Thanks for the report. Everything should be fixed in: https://github.com/lineagedr/mod-bountyhunter/commit/cc40a10c6835add05023b3b81edee840640237be
