### ISSUE TITLE
New idea: Bounty for characters from both Alliance/Horde factions

### ISSUE THREAD

**Issue by yuanf225** [lineagedr/mod-bountyhunter#3]
1、Bounty for characters from both Alliance/Horde factions
2、After receiving the bounty, the character gets a debuff, which can kill any player in the Alliance/Horde, and players from any faction can also kill the player who received the bounty.
3、The debuff will be removed after submitting the bounty

**Comment by lineagedr** [comment]
These require core edits. It cannot be done with just a module.
