### ISSUE TITLE
warning: unused parameter 'sender' [-Wunused-parameter]

### ISSUE THREAD

**Issue by yuanf225** [lineagedr/mod-bountyhunter#4]
![image](https://user-images.githubusercontent.com/43561197/191022826-d32a2022-41f9-4e84-be5a-a3ed8e0402f1.png)

/home/azerothcore-wotlk/modules/mod-bountyhunter/src/BountyHunter_SC.cpp:123:68: warning: unused parameter 'sender' [-Wunused-parameter]
    bool OnGossipSelect(Player* player, Creature* creature, uint32 sender, uint32 action) override

**Comment by lineagedr** [comment]
https://github.com/lineagedr/mod-bountyhunter/commit/e3f7ee3fc43770b78c5d3b30cedcce5afdd9ce32
